app = "shader-backend-anura"
primary_region = "iad"  # Choose your region, e.g., iad (Ashburn, VA)

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "4000"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0